module Constants
  BREAKFIRST_SINGLE_TICKET = 190
  BREAKFIRST_MULTI_TICKET  = 170

  LUNCH_SINGLE_TICKET      = 290
  LUNCH_MULTI_TICKET       = 260

  DINNER_SINGLE_TICKET     = 390
  DINNER_MULTI_TICKET      = 420

  BREAKFIRST_NUM           = 0
  LUNCH_NUM                = 1
  DINNER_NUM               = 2
end
